symbols_embedding_dim: 256
in_fft_n_layers: 4
in_fft_n_heads: 1
in_fft_d_head: 32
in_fft_conv1d_kernel_size: 7
in_fft_conv1d_filter_size: 256
in_fft_output_size: 256
p_in_fft_dropout: 0.1
p_in_fft_dropatt:  0.1
p_in_fft_dropemb: 0
out_fft_n_layers: 4
out_fft_n_heads: 1
out_fft_d_head: 32
out_fft_conv1d_kernel_size: 7
out_fft_conv1d_filter_size: 256
out_fft_output_size: 256
p_out_fft_dropout: 0.1
p_out_fft_dropatt: 0.1
p_out_fft_dropemb: 0.0
speaker_emb_weight: 1
